name: "Documentation Upload"

on:
  push:
    branches: [ main, master ]
    tags:
      - v1.*

jobs:
  Documentation-Generation-And-Upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq python3-sphinx graphviz python-six texlive-fonts-recommended texlive-latex-extra texlive-plain-generic texlive-latex-recommended latexmk texlive-fonts-extra
          pip install sphinx-rtd-theme
      - name: Build Documentation
        run: source tools/ci.sh && build_docs_pdf
      - name: Checkout Website Repository
        uses: actions/checkout@v4
        with:
          repository: opcua/opcua-www
          path: opcua-www
          ref: main
          persist-credentials: false
      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF##*/}"
        id: myref
      - name: Copy Documentation Files to Website repository
        run: |
          rm -r -f ./opcua-www/static/doc/${{ steps.myref.outputs.branch }} || true # ignore result
          mkdir ./opcua-www/static/doc/${{ steps.myref.outputs.branch }} || true # ignore result
